#!/bin/bash

#SBATCH -J test
#SBATCH -n 24
#SBATCH -N 1
#SBATCH -p haswell
#SBATCH --time=3:00:00
#SBATCH --mem-per-cpu=2583
#SBATCH -A p_magmof

#############
# VARIABLES #
#############
CORES=24
OMP=24
MKL=1
wdir=$(echo `pwd`)
#
# Note: The scratch folder is named the same as the working folder 
#       Thus is bad idea for running the jobs with the same folder name!
folder=$(echo `pwd` | rev | cut -d'/' -f1 | rev)
scratch=$SCRATCH/${folder}

#################### 
# EXPORT VARIABLES #
####################
export OMP_NUM_THREADS=$CORES
export MKL_NUM_THREADS=$MKL
export OMP_NESTED=false
export OMP_DYNAMIC=false

# cleaning up every module 
module --force purge
# this is needed because pyscf/pyflosic was build with this modules 
#module load modenv/both modenv/classic python/2.7.5-scipy
module load modenv/scs5 pyscf/1.6.0-intel-2018a-Python-3.6.4

# mkl
export LD_PRELOAD=$MKLROOT/lib/intel64/libmkl_avx2.so:$MKLROOT/lib/intel64/libmkl_sequential.so:$MKLROOT/lib/intel64/libmkl_core.so
# pyscf
#export PYTHONPATH=/home/trepte/programs/ase/:$PYTHONPATH
# pyflosic 
export PYTHONPATH=/projects/p_magmof/pyflosic_clean/src/:$PYTHONPATH
export PYTHONPATH=/projects/p_magmof/pyflosic_clean/utils/:$PYTHONPATH


mkdir $scratch
cp -r -p * $scratch
cd $scratch
python3.5 run_test.py -v 1> pyflosic.out 2> pyflosic_error.out
cp -r -p $scratch/* $wdir
cd $wdir
exit

