#!/bin/bash

#SBATCH -J run_test 
#SBATCH --get-user-env
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --partition=calcium,sulfur,magnesium,cuda,chrom
#SBATCH --mail-type=end
#SBATCH --export=ALL
#SBATCH --time=23:59:00

username=schwalbe
ncpus=20

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/sw/intel/intel2015/composer_xe_2015.3.187/mkl/lib/intel64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/sw/gfortran/lib64

# check at which hist we did really end up
hn=$(hostname)

if [[ $hn == "calcium"* ]]; then  ncpus=20;  fi
if [[ $hn == "sulfur"* ]]; then  ncpus=16;  fi
if [[ $hn == "magnesium"* ]]; then  ncpus=12;  fi
if [[ $hn == "chrom"* ]]; then  ncpus=24;  fi
if [[ $hn == "cuda"* ]]; then  ncpus=24;  fi

JOB_WDIR=`pwd`

cd $JOB_WDIR

# scratch
mkdir /local/scratch/$username

tmpdir=$(mktemp --tmpdir=/local/scratch/$username -d )

## cp everything to scratch
cp -p -r * $tmpdir/
echo "$tmpdir" > TMPDIR
cd $tmpdir

echo ">>>>> Cores: $ncpus <<<<<<"

export OMP_NUM_THREADS=$ncups
export MKL_NUM_THREADS=1

export PYTHONPATH=/home/schwalbe/__Programms__/pyscf_v3/pyscf/:$PYTHONPATH
pyflosic=/home/schwalbe/__Programms__/pyflosic/
export PYTHONPATH=$pyflosic/src/:$PYTHONPATH
export PYTHONPATH=$pyflosic/utils/:$PYTHONPATH

python3.5 -W ignore run_test.py -v 1> pyflosic.out 2> pyflosic_error.out

## copy everything back
cp -p -r * $JOB_WDIR/
cd $JOB_WDIR
rm -rf $tmpdir

exit
